.TH DABROWSE 1 "2025-12-30" "dumbass-tree" "User Commands"
.SH NAME
dabrowse \- open URLs in a terminal browser
.SH SYNOPSIS
.B dabrowse
[\-\-engine auto|carbonyl|browsh|w3m|links|elinks|lynx]
.I <url-or-path>
.SH DESCRIPTION
dabrowse picks the best available terminal browser (carbonyl, browsh, w3m, links, lynx)
and runs it. This is a convenience launcher.
.SH SEE ALSO
browsh(1), lynx(1), w3m(1)
