.TH DAX 1 "2025-12-31" "dumbass-tree" "User Commands"
.SH NAME
dax \- show whether you're on X11 or Wayland
.SH SYNOPSIS
.B dax
.I status|explain
.SH DESCRIPTION
dax prints a small set of signals that help you understand whether your current session is using X11 or Wayland,
and whether XWayland is running for legacy applications.
.SH SEE ALSO
loginctl(1)
